#!/bin/env python

import subprocess

banner = """
                                                        #
#                                   #     #            ###
#       ###### #    # ###### #      #     # #####     #####
#       #      #    # #      #      #     # #    #   #######
#       #####  #    # #####  #      #     # #    #  #########
#       #      #    # #      #      #     # #####  ###########
#       #       #  #  #      #      #     # #        #######
####### ######   ##   ###### ######  #####  #        #######

"""
print(banner)

name: str = ""
while not name:
    name = input(
        "Please enter your full name, as you would like it displayed in GitHub: "
    )

email: str = ""
while "@" not in email:
    email = input(
        "Please enter the email address associated with your GitHub account: "
    )

print("\nConfiguring git with the information you provided...\n")
subprocess.run(["git", "config", "--global", "user.email", email])
subprocess.run(["git", "config", "--global", "user.name", name])
subprocess.run(["git", "config", "--global", "--unset", "credential.helper"])

print("\nGit is now configured with the settings below.\n")
result = subprocess.run(["git", "config", "--global", "-l"], stdout=subprocess.PIPE)
print(result.stdout.decode("utf-8"))
print("\nIf your name or email is incorrect, please re-run this command.\n")
