#!/bin/env python

import subprocess
import shlex

banner = """
                                                        #
#                                   #     #            ###
#       ###### #    # ###### #      #     # #####     #####
#       #      #    # #      #      #     # #    #   #######
#       #####  #    # #####  #      #     # #    #  #########
#       #      #    # #      #      #     # #####  ###########
#       #       #  #  #      #      #     # #        #######
####### ######   ##   ###### ######  #####  #        #######

"""
print(banner)

print("\nSyncing your local repo with the remote...\n")
commands = [
    "git checkout main",
    "git fetch origin",
    "git reset origin/main --hard",
    "git clean -fdx",
    "git pull",
]
for cmd in commands:
    result = subprocess.run(shlex.split(cmd), stdout=subprocess.PIPE)
    print(result.stdout.decode("utf-8"))
    if result.returncode < 0:
        exit(1)

print("\nYour local repo is now in sync with the [main] branch on the remote.\n")
