#!env python3

import subprocess
import argparse
import shlex
from functools import lru_cache

BANNER = """
                                                        #
#                                   #     #            ###
#       ###### #    # ###### #      #     # #####     #####
#       #      #    # #      #      #     # #    #   #######
#       #####  #    # #####  #      #     # #    #  #########
#       #      #    # #      #      #     # #####  ###########
#       #       #  #  #      #      #     # #        #######
####### ######   ##   ###### ######  #####  #        #######

"""

SYNCPOINT_BRANCH_PREFIX = "syncpoint"


def get_commit_hash_of_branch(branch_name):
    result = subprocess.run(
        f"git rev-parse --short --verify {branch_name}",
        stdout=subprocess.PIPE,
        shell=True,
    )
    if result.returncode < 0:
        exit(1)
    return result.stdout.decode("utf-8").strip()


@lru_cache
def get_available_syncpoints():
    result = subprocess.run(["git", "branch", "-a"], stdout=subprocess.PIPE)
    branch_list = [
        x.strip().replace("remotes/origin/", "")
        for x in result.stdout.decode("utf-8").splitlines()
    ]
    return [x for x in branch_list if x.startswith(SYNCPOINT_BRANCH_PREFIX)]


def save_current_state_to_tag():
    commit_hash = get_commit_hash_of_branch("main")
    commands = [
        f"git tag save-{commit_hash}",
    ]
    for cmd in commands:
        print(cmd)
        result = subprocess.run(shlex.split(cmd), stdout=subprocess.PIPE)
        print(result.stdout.decode("utf-8"))
        if result.returncode < 0:
            exit(1)


def reset_to_syncpoint(syncpoint):
    commit_hash = get_commit_hash_of_branch(syncpoint)
    commands = [
        f"git checkout {syncpoint}",
        "git pull",
        f"git checkout {commit_hash}",
        "git branch -f main HEAD",
        "git checkout main",
        "git pull --rebase",
        "git push -u origin main --tags",
    ]
    for cmd in commands:
        print(cmd)
        result = subprocess.run(shlex.split(cmd), stdout=subprocess.PIPE)
        print(result.stdout.decode("utf-8"))
        if result.returncode < 0:
            exit(1)


def main():
    print(BANNER)
    parser = argparse.ArgumentParser(
        prog="lvlup-git-syncpoint",
        description="Reset origin/main to selected syncpoint",
    )
    parser.add_argument(
        "syncpoint",
        nargs="?",
        choices=get_available_syncpoints(),
        type=str,
        help="<= select one of these",
    )

    args = parser.parse_args()
    subprocess.run(["git", "fetch"])
    save_current_state_to_tag()
    reset_to_syncpoint(args.syncpoint)


if __name__ == "__main__":
    main()
